const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.wrap,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.TiledBg.Exps.ColorValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Tilemap.Cnds.IsVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Tilemap.Acts.SetDefaultColor,
		C3.Plugins.Keyboard.Cnds.OnAnyKey
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Sólido: 0},
	{cama: 0},
	{fundo1: 0},
	{tpgalpao: 0},
	{Vídeo: 0},
	{Vídeo3: 0},
	{Áudio: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{DarAVolta: 0},
	{player: 0},
	{MoverPara: 0},
	{CampoDeVisão: 0},
	{inimigo1: 0},
	{robozin: 0},
	{Texto: 0},
	{alerta: 0},
	{save: 0},
	{Sprite: 0},
	{Piscar: 0},
	{tutorial: 0},
	{Esmaecer: 0},
	{Sprite2: 0},
	{Mosaico: 0},
	{nomejg: 0},
	{Fixar: 0},
	{player2: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite4: 0},
	{Texto5: 0},
	{Mosaico2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{portalado: 0},
	{portalado2: 0},
	{dialogo: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{alertxt: 0},
	{dialogorobo: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{portalado3: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Texto6: 0},
	{livroAberto: 0},
	{portacasa: 0},
	{portacasa2: 0},
	{Texto7: 0},
	{Sprite28: 0},
	{Texto8: 0},
	{MoverPara2: 0},
	{CampoDeVisão2: 0},
	{Perseguidores: 0},
	{textura: 0},
	{morteInicial: 0},
	{morteInicial2: 0},
	{comeco: 0},
	{opacidade: 0},
	{tuto: 0},
	{DASH: 0},
	{cor: 0},
	{cor2: 0},
	{shift: 0},
	{musica: 0},
	{robosegue: 0},
	{robot: 0},
	{chip: 0},
	{freeze: 0},
	{timer: 0},
	{CheckpointX: 0},
	{CheckpointY: 0},
	{Trocar: 0},
	{dorm: 0},
	{alarm: 0},
	{dep: 0},
	{Log: 0},
	{casa1: 0},
	{pause: 0},
	{Fcasa: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	cama: class extends self.ISpriteInstance {},
	fundo1: class extends self.ITiledBackgroundInstance {},
	tpgalpao: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo3: class extends self.IWorldInstance {},
	Áudio: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	robozin: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	alerta: class extends self.ISpriteInstance {},
	save: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	tutorial: class extends self.IWorldInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	nomejg: class extends self.ITextInstance {},
	player2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	portalado: class extends self.ISpriteInstance {},
	portalado2: class extends self.ISpriteInstance {},
	dialogo: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	alertxt: class extends self.ITextInstance {},
	dialogorobo: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	portalado3: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	livroAberto: class extends self.ISpriteInstance {},
	portacasa: class extends self.ISpriteInstance {},
	portacasa2: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Perseguidores: class extends self.ISpriteInstance {},
	textura: class extends self.ISpriteInstance {}
}