const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Tileset: 0},
	{Casinha: 0},
	{Cogumelo: 0},
	{Feno: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Vaquinha: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Saida: 0},
	{stop: 0},
	{Mosaico: 0},
	{Mosaico2: 0},
	{Triangulo: 0},
	{Cerca: 0},
	{Mosaico3: 0},
	{Texto: 0},
	{Sprite3: 0},
	{BarraDeProgresso: 0},
	{potuação: 0},
	{TextoPontuação: 0},
	{stop2: 0},
	{Texto2: 0},
	{play: 0},
	{Pontuacao: 0}
];

self.InstanceType = {
	Tileset: class extends self.ITilemapInstance {},
	Casinha: class extends self.ISpriteInstance {},
	Cogumelo: class extends self.ISpriteInstance {},
	Feno: class extends self.ISpriteInstance {},
	Vaquinha: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Saida: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Triangulo: class extends self.ISpriteInstance {},
	Cerca: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	TextoPontuação: class extends self.ITextInstance {},
	stop2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {}
}