const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.MoveTo,
		C3.Behaviors.EightDir,
		C3.Plugins.shadowlight,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Plugins.Tilemap,
		C3.Plugins.Timeline,
		C3.Plugins.sliderbar,
		C3.Behaviors.Timer,
		C3.Plugins.video,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.video.Acts.SetSampling,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{OIP: 0},
	{OIP2: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{ProjetorDeSombra: 0},
	{MoverPara: 0},
	{"8Direções": 0},
	{Sprite4: 0},
	{OIP3: 0},
	{OIP4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{R: 0},
	{OIP5: 0},
	{R2: 0},
	{Refletor: 0},
	{Texto: 0},
	{images: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{OIP6: 0},
	{Teclado: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{iris: 0},
	{Sprite: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Fixar: 0},
	{irisAnimações: 0},
	{Mosaico: 0},
	{Mosaico2: 0},
	{nuvens: 0},
	{Sprite20: 0},
	{Sprite19: 0},
	{Sprite21: 0},
	{morpheus: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{ControladorDaTimeline: 0},
	{Cronômetro: 0},
	{BarraDeslizante: 0},
	{Sprite24: 0},
	{Mosaico3: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Vídeo: 0},
	{Texto2: 0},
	{Sprite28: 0},
	{Texto3: 0},
	{Texto4: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{life: 0}
];

self.InstanceType = {
	OIP: class extends self.ISpriteInstance {},
	OIP2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	OIP3: class extends self.ISpriteInstance {},
	OIP4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	R: class extends self.ISpriteInstance {},
	OIP5: class extends self.ISpriteInstance {},
	R2: class extends self.ISpriteInstance {},
	Refletor: class extends self.IShadowLightInstance {},
	Texto: class extends self.ITextInstance {},
	images: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	OIP6: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	iris: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	irisAnimações: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	nuvens: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	morpheus: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	ControladorDaTimeline: class extends self.IInstance {},
	BarraDeslizante: class extends self.ISliderBarInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {}
}