const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Persist,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Behaviors.LOS.Acts.ClearObstacles,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.LOS.Exps.Range,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerOpacity
	];
};
self.C3_JsPropNameTable = [
	{BI: 0},
	{para_move: 0},
	{Sólido: 0},
	{Persistir: 0},
	{bloco: 0},
	{hitboxDoBloco: 0},
	{apareceF: 0},
	{IL: 0},
	{ligamento_door: 0},
	{alavanca: 0},
	{IP: 0},
	{Conexão: 0},
	{ligado: 0},
	{portal: 0},
	{relembra: 0},
	{memoria: 0},
	{IT: 0},
	{layout: 0},
	{sala: 0},
	{textoPlayer: 0},
	{Texto: 0},
	{ITe: 0},
	{texto_falar: 0},
	{poder_falar: 0},
	{tempo: 0},
	{tempoEscreve: 0},
	{falar: 0},
	{parede2: 0},
	{playerTexto: 0},
	{esta_vivo: 0},
	{empurando: 0},
	{está_andando: 0},
	{Fixar: 0},
	{animationPlayer: 0},
	{pulando: 0},
	{tem_camera: 0},
	{tecla: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Playe: 0},
	{mortal: 0},
	{playerColidiu: 0},
	{viu_algo: 0},
	{atodoador: 0},
	{tempo_atod: 0},
	{CampoDeVisão: 0},
	{inimigo: 0},
	{morte: 0},
	{parede: 0},
	{vertical: 0},
	{horizontal: 0},
	{velocidae: 0},
	{IPl: 0},
	{Senóide: 0},
	{plataforma: 0},
	{IDo: 0},
	{ala_ligamneto: 0},
	{porta: 0},
	{fase: 0},
	{proximaFase: 0},
	{Teclado: 0},
	{teklas: 0},
	{visao: 0},
	{flashe: 0},
	{Mouse: 0},
	{Sprite: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite2: 0},
	{Texto4: 0},
	{Mosaico: 0},
	{PlanoDeFundoEmBlocos: 0},
	{letal: 0},
	{teclaF: 0},
	{Qual_IL: 0},
	{Qual_lingamento: 0},
	{on_ala: 0},
	{ala_on: 0},
	{Qual_ID: 0},
	{Qual_door_ligamento: 0},
	{QualEIp: 0},
	{Qual_IP_conexao: 0},
	{on_portal: 0},
	{posição_Y_salva: 0},
	{posição_X_salva: 0},
	{qual_IT: 0},
	{pegouACamera: 0},
	{destruindos: 0},
	{plataformas_existentes: 0},
	{plataforma_selecionada: 0},
	{hori: 0},
	{veti: 0},
	{qual_BI: 0},
	{colidi_bloco: 0},
	{continuar: 0},
	{Posicao_x_atual: 0},
	{posicao_y_atual: 0},
	{qual_falar: 0},
	{layoutAtual: 0}
];

self.InstanceType = {
	bloco: class extends self.ISpriteInstance {},
	hitboxDoBloco: class extends self.ISpriteInstance {},
	alavanca: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	memoria: class extends self.ISpriteInstance {},
	sala: class extends self.ISpriteInstance {},
	textoPlayer: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	falar: class extends self.ISpriteInstance {},
	parede2: class extends self.ISpriteInstance {},
	playerTexto: class extends self.ITextInstance {},
	animationPlayer: class extends self.ISpriteInstance {},
	Playe: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	proximaFase: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	teklas: class extends self.ISpriteInstance {},
	visao: class extends self.ISpriteInstance {},
	flashe: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	letal: class extends self.ISpriteInstance {},
	teclaF: class extends self.ISpriteInstance {}
}