const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Tween,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{parededigital2: 0},
	{parede2: 0},
	{parede: 0},
	{parededigital: 0},
	{portaDeslizando: 0},
	{botaoLARANJA: 0},
	{botaoVermelho: 0},
	{botaoROSA: 0},
	{botaoVERDE: 0},
	{portaLAabrindo: 0},
	{paredeLaranja: 0},
	{PortaPKAbrindo: 0},
	{paredeRosa: 0},
	{PortaVDabrindo: 0},
	{paredeVerde: 0},
	{botao03sheet: 0},
	{btRoseAberto: 0},
	{BTRose: 0},
	{BTAmarelo: 0},
	{BTAzul2: 0},
	{espinhocromac01sheet: 0},
	{pontofinalX: 0},
	{pontofinalY: 0},
	{PontoFinalPlayerX: 0},
	{PontoFinalPlayerY: 0},
	{portaal: 0},
	{botao03sheet2: 0},
	{CentrarEm: 0},
	{Senóide: 0},
	{carraotonhao: 0},
	{Projétil: 0},
	{bala: 0},
	{andando_esquerda: 0},
	{Plataforma: 0},
	{carrinJuninDIGITAL: 0},
	{andando__esquerda: 0},
	{carrinJuninREAL: 0},
	{ROBOBERTO: 0},
	{fofoqueiros: 0},
	{camera: 0},
	{Fixar: 0},
	{carrinjunin: 0},
	{chave: 0},
	{LaserAbrindo: 0},
	{laserAzul: 0},
	{PortaAbrindo: 0},
	{laserROSE: 0},
	{laser: 0},
	{lazerazuul: 0},
	{logo: 0},
	{ordemBotaoMenu: 0},
	{nomeBotaoMenu: 0},
	{txt_OpcoesMenu: 0},
	{Botão: 0},
	{gameover: 0},
	{pause: 0},
	{play: 0},
	{quit: 0},
	{mouse: 0},
	{Teclado: 0},
	{personagemanimacao: 0},
	{Direcao_Dash: 0},
	{ativo_dash: 0},
	{PortalCoolDown: 0},
	{"8Direções": 0},
	{jogador: 0},
	{galpaoTilesdigital: 0},
	{metrostaiontilesetsheetsheetTiaFaby: 0},
	{PularAtravés: 0},
	{mosaicDigital: 0},
	{mosaicReal: 0},
	{devinitovoExpositorTiseletNivel1: 0},
	{devinitovoExpositorTiseletNivel2: 0},
	{metrostaiontilesetsheet2: 0},
	{tilesetservidorsheet: 0},
	{galpaoTileREal: 0},
	{AreaResidencialBGSemFundo1: 0},
	{ÁreaResidêncialMBG2: 0},
	{fundoservidor: 0},
	{Interpolação: 0},
	{quadradoinvisivel: 0},
	{Sprite: 0},
	{chaoinvi: 0},
	{imagem: 0},
	{GalpaumDIGITAL: 0},
	{canhaotonhao: 0},
	{canhaos2: 0},
	{ArmazenamentoLocal: 0},
	{escadaDeMao01sheet2: 0},
	{persoEscada: 0},
	{GalpaumREAL: 0},
	{imagem2: 0},
	{criadores: 0},
	{portaserver: 0},
	{SuporteDeArmazem01QH: 0},
	{lixeiraOffeco01sheet: 0},
	{inimigos: 0},
	{familiaMosaic: 0},
	{cartao: 0},
	{esta_digital: 0},
	{botaoverm: 0},
	{perta_botao: 0},
	{subirEscada: 0}
];

self.InstanceType = {
	parededigital2: class extends self.ITilemapInstance {},
	parede2: class extends self.ITilemapInstance {},
	parede: class extends self.ITilemapInstance {},
	parededigital: class extends self.ITilemapInstance {},
	portaDeslizando: class extends self.ISpriteInstance {},
	botaoLARANJA: class extends self.ISpriteInstance {},
	botaoVermelho: class extends self.ISpriteInstance {},
	botaoROSA: class extends self.ISpriteInstance {},
	botaoVERDE: class extends self.ISpriteInstance {},
	paredeLaranja: class extends self.ISpriteInstance {},
	paredeRosa: class extends self.ISpriteInstance {},
	paredeVerde: class extends self.ISpriteInstance {},
	botao03sheet: class extends self.ISpriteInstance {},
	BTRose: class extends self.ISpriteInstance {},
	BTAmarelo: class extends self.ISpriteInstance {},
	BTAzul2: class extends self.ISpriteInstance {},
	espinhocromac01sheet: class extends self.ISpriteInstance {},
	portaal: class extends self.ISpriteInstance {},
	botao03sheet2: class extends self.ISpriteInstance {},
	carraotonhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	carrinJuninDIGITAL: class extends self.ISpriteInstance {},
	carrinJuninREAL: class extends self.ISpriteInstance {},
	ROBOBERTO: class extends self.ISpriteInstance {},
	fofoqueiros: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	carrinjunin: class extends self.ISpriteInstance {},
	chave: class extends self.ISpriteInstance {},
	laserAzul: class extends self.ISpriteInstance {},
	laserROSE: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	lazerazuul: class extends self.ISpriteInstance {},
	logo: class extends self.ITextInstance {},
	txt_OpcoesMenu: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	gameover: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	quit: class extends self.ISpriteInstance {},
	mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	personagemanimacao: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	galpaoTilesdigital: class extends self.ITilemapInstance {},
	metrostaiontilesetsheetsheetTiaFaby: class extends self.ITilemapInstance {},
	mosaicDigital: class extends self.ITilemapInstance {},
	mosaicReal: class extends self.ITilemapInstance {},
	devinitovoExpositorTiseletNivel1: class extends self.ISpriteInstance {},
	devinitovoExpositorTiseletNivel2: class extends self.ISpriteInstance {},
	metrostaiontilesetsheet2: class extends self.ITilemapInstance {},
	tilesetservidorsheet: class extends self.ITilemapInstance {},
	galpaoTileREal: class extends self.ITilemapInstance {},
	AreaResidencialBGSemFundo1: class extends self.ISpriteInstance {},
	ÁreaResidêncialMBG2: class extends self.ISpriteInstance {},
	fundoservidor: class extends self.ISpriteInstance {},
	quadradoinvisivel: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chaoinvi: class extends self.ISpriteInstance {},
	imagem: class extends self.ISpriteInstance {},
	GalpaumDIGITAL: class extends self.ISpriteInstance {},
	canhaotonhao: class extends self.ISpriteInstance {},
	canhaos2: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	escadaDeMao01sheet2: class extends self.ISpriteInstance {},
	persoEscada: class extends self.ISpriteInstance {},
	GalpaumREAL: class extends self.ISpriteInstance {},
	imagem2: class extends self.ISpriteInstance {},
	criadores: class extends self.ITextInstance {},
	portaserver: class extends self.ISpriteInstance {},
	SuporteDeArmazem01QH: class extends self.ISpriteInstance {},
	lixeiraOffeco01sheet: class extends self.ISpriteInstance {},
	inimigos: class extends self.ISpriteInstance {},
	familiaMosaic: class extends self.ITilemapInstance {}
}