const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{coelhiiiinnn2: 0},
	{coelhiiiinnn1: 0},
	{objetos: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{persoIdle: 0},
	{Teclado: 0},
	{Sprite: 0},
	{cenoura: 0},
	{vidas: 0},
	{PONTOS: 0},
	{VIDA: 0},
	{Sprite0001: 0},
	{Sprite2: 0},
	{ceuNoite: 0},
	{cenoura2: 0},
	{Piscar: 0},
	{fake: 0},
	{cenoura3: 0},
	{objetos2: 0},
	{correr: 0},
	{PONTUACAO: 0},
	{correr2: 0},
	{VIDA2: 0},
	{PONTUACAO2: 0},
	{correr3: 0},
	{PONTUACAO3: 0},
	{VIDA3: 0},
	{correr4: 0},
	{PONTUACAO4: 0},
	{VIDA4: 0}
];

self.InstanceType = {
	coelhiiiinnn2: class extends self.ITilemapInstance {},
	coelhiiiinnn1: class extends self.ITilemapInstance {},
	objetos: class extends self.ITilemapInstance {},
	persoIdle: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	cenoura: class extends self.ISpriteInstance {},
	vidas: class extends self.ISpriteInstance {},
	PONTOS: class extends self.ITextInstance {},
	VIDA: class extends self.ITextInstance {},
	Sprite0001: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ITiledBackgroundInstance {},
	ceuNoite: class extends self.ITiledBackgroundInstance {},
	cenoura2: class extends self.ISpriteInstance {},
	fake: class extends self.ISpriteInstance {},
	cenoura3: class extends self.ISpriteInstance {},
	objetos2: class extends self.ITilemapInstance {}
}